version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo-dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: seu_usuario
      MONGO_INITDB_ROOT_PASSWORD: sua_senha
      MONGO_INITDB_DATABASE: nome_do_banco
    volumes:
      - ./data/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro